### ISSUE TITLE
Route not found error

### ISSUE THREAD

**Issue by RupertB-ES** [TheAxeDude/ZiniGo#44]
Got this error after logging in

GotLogin
Fetching Library
Fetching page:1
{"status":false,"error":{"message":"Route not found in ApiRouter","internal_code":"CONTENT_ERROR"}}
Terminating the application...

**Comment by jmskuo** [comment]
I get the error message is {"status":false,"error":{"message":"Route not found in ApiRouter","internal_code":"APPERR13131313"}}

**Comment by dirty1200** [comment]
now i also get  
{"status":false,"error":{"message":"Route not found in ApiRouter","internal_code":"APPERR13131313"}}

**Comment by gabag30** [comment]
same here, I was trying to backup my library and run into the issue. Is there any plan to update the tool?

**Comment by ms162223** [comment]
I am getting this error as well.  I would love to see the project updated.  Does anyone know of any alternatives.  I have ton of magazines that I have been subscribing to for years and now Zinio wants you to pay monthly for access to old issues that you already paid for.

**Comment by muttmutt** [comment]
Same error on both MacOS 14.6.1 and on Ubuntu 22.04.

**Comment by TheAxeDude** [comment]
Looks like Zinio have made a few changes to their backend. I have gotten past the original problem raised, but have encountered a few more - will work on those.

**Comment by TheAxeDude** [comment]
It looks like Zinio no longer has the older SVG-based reader, which this tool was based on. This may be a major roadblock - we will need to look into how their PDF-based reader works. In the long run, this should be better - but will take some time.

**Comment by ER-EPR** [comment]
I have successfully fix this problem, it's only because of the get library api changes, the keys now are 'library-issues' 'offset'. And in order to terminate process this change is also needed `pageToFetch += issuesToFetch`
```
func GetLibrary(userToken LoginResponse, endpoint string) []LibraryResponse {
	fmt.Println("Fetching Library")
	client := &http.Client{}

	var itemsToReturn []LibraryResponse
	issuesToFetch := 120

	pageToFetch := 0
	for {
		fmt.Println("Fetching page:" + strconv.Itoa(pageToFetch))

		req, _ := http.NewRequest("GET", "https://zinio.com/api/newsstand/newsstands/101/users/"+userToken.Data.User.UserIDString+"/library-issues?limit="+strconv.Itoa(issuesToFetch)+"&offset="+strconv.Itoa(pageToFetch), nil)

		req.Header.Add("Content-Type", "application/json")
		for _, cookie := range userToken.Data.Cookies {
			req.AddCookie(cookie)
		}
		//req.AddCookie(&http.Cookie{Name: "zwrt", Value: userToken.Data.AccessToken})
		//req.Header.Add("Authorization", "bearer "+userToken.Data.Token.AccessToken)
		//req.Header.Add("Authorization", initialToken)

		resp, err := client.Do(req)

		if err != nil {
			fmt.Println("Unable to get Library: " + err.Error())
		}

		data, _ := ioutil.ReadAll(resp.Body)
		fmt.Println(string(data))

		responseType := LibraryResponse{}

		_ = json.Unmarshal(data, &responseType)

		if len(responseType.Data) > 0 {
			itemsToReturn = append(itemsToReturn, responseType)
			pageToFetch += issuesToFetch
		} else {
			break
		}
	}

	return itemsToReturn
}
```
BTW, the changes I made are based on @motoyugota 's fork.

**Comment by SR-G** [comment]
I can confirm that it's now working ! Good job.

```bash
git clone https://github.com/motoyugota/ZiniGo/
cd ZiniGo
git checkout fixgetpages
cd ZiniGo
vi main.go   # then just replace the whole content of the "GetLibrary" method

go build .

mkdir "issue/"  # otherwise weird permissions ... but still, generated files have now weird permissions
cp ../built/template.html .
./ZiniGo

```

But in the generated .PDF, i have a weird "PDF note" (small note in top left corner) everywhere (with the content "page=Cover", etc.). Was not happening before / don't know from where this is coming. The template.html ?

**Comment by SR-G** [comment]
Ok so i still don't know from where these "notes" (it seems to be "sticky notes"), but to remove them, i just had to add (line 186) : 

```go
			_ = api.MergeCreateFile(filenames, completeName, nil)
			err2 := api.RemoveAnnotationsFile(completeName, "", nil, nil, nil, nil, false)
			if err2 != nil {
				fmt.Println(err2)
			}
```

**Comment by SR-G** [comment]
Ok, so now that it's running in batch, it's of course way better, but there are still sometimes some issues (i have no idea why) - sometimes, the whole download is working 100% fine (target .PDF is fully valid), and sometimes i have many times these errors (sometimes for all the pages, sometimes for a subset)

```
Removing extra pages failed with pdfcpu: please provide the correct password
.retrying after error: pdfcpu: please provide the correct password
```

(resulting of course in a target "0 bytes" .PDF)

**Comment by shmimel** [comment]
@SR-G, nothing more exciting than seeing fresh comments on a repo! Nice job :) Last month I wrote an AHK script that prints each individual page to PDF and combines into one big one because I didn't have the skills to troubleshoot...

**Comment by ER-EPR** [comment]
@SR-G I was hoping I can fix those problem after I learn some more golang. I've never coded in go. I don't know why I got a `.\main.go:142:12: undefined: model` following your instructions. I modified go.mod and use go mode tidy to update. But it seems you also change some names of the variant?

**Comment by ER-EPR** [comment]
After a `go get -u ./...` run in the same directory with go.mod and go.sum. The error was gone and it works perfectly. Thanks @SR-G

**Comment by SR-G** [comment]
Sadly the `pdfcpu` (which i don't know well) seems to not be very flexible : 
- they removed the "ValidationNone" feature (as visible in other issues of the project)
- as a consequence, any error in the PDF prevents it to be processed by this library
- it seems that when there are "weird date pattern", they are manually adding "local corrections" inside the library ... but it's an endless job and IMHO not the proper approach

So there are several options : 
1. Use `pdfcpu` to remove "Keywords" (= to blank the dates) : pretty sure this will fail, as their "validation" step will still be applied in the `api.RemoveKeywordsFile()` operation
2. Have `pdfcpu` locally correct their date parsing regarding the encountered error : again, endless job, new issues may be encountered here and there again and again over time
3. Find another golang PDF library (at least to "clean" the keywords / metadata in the PDF before `pdfcpu` is triggered)
4. At worst, clean up the metadata in another way (for example, even if it's an horrible solution ..., by triggering the remote command `pdftk` on the generated files, and use it to remove the metadata (it's an ugly solution as it would fork another CLI process for each page that needs to be cleaned ...))

(i'm speaking about "cleaning up the metadata" in order to "prepare" the temporary .PDF and have them ready to be processed by `pdfcpu` as it is nowadays in the ZiniGo code)

**Comment by ER-EPR** [comment]
I tried https://github.com/sfomuseum/go-pdfbox.git and https://pkg.go.dev/github.com/KarmaPenny/pdfparser

**Comment by TheAxeDude** [comment]
@ER-EPR  in my last experiments, it seemed that Zinio had stopped using the "Legacy" flag to mark files, and set the PDF. Unfortunately, my library isnt very big so none of my issues actually used this. 

It almost seemed at some point like every other page was using a different password.

I have got a version using c# (Im a lot more familiar with c# than golang - this was just an experimental project for me) which I can try to get cleaned up and uploaded here.

Im not sure if makes sense to archive this repo and move to a new one, anyone have thoughts?

**Comment by RupertB-ES** [comment]
I think it would be best to "cap" the go archive with a build with the main extract fix in it and create a new C# archive

**Comment by SR-G** [comment]
But i don't understand @TheAxeDude your last comment - with the previous comments from yesterday, a lot of things are still working here : 
- API issues solved : issues are found in library, pages are found again in issues
- .SVG / .PDF download is working fine
- no more issue with password (some files are NOT password protected, some files are decrypted with the password of the user)
- extra sticky notes are easily removable
- extra issues are solved by upgrading the pdfcpu

What remains seems only to be (for SOME of the pages downloaded) the weird date, at this time unparseable by the PDFCPU library.
But, again, it's working fine now (since yesterday) for most files.

**Comment by dirty1200** [comment]
im no coder at all!
how go i make a go file?
i have go installed and visual studio code installed.
im on OSX

thanks!

**Comment by SR-G** [comment]
@ER-EPR So, i made a few extra tests (after having been able to be in a situation with the same wrong date than you), and i think i've understood a few things.

**First, many issues were coming from the failure of executions at 'decrypt time'**

The biggest problem has been since a long time the fact that ... all errors at decrypt time are hidden : 

```go
os.WriteFile(pathString+".pdf", html, 0644)
api.DecryptFile(pathString+".pdf", "", conf)
```

So in case of failures here, everything else was broken (and no valid PDF in the end) : and this is why sometimes some temporary pages were found on disk and were asking for a password : because decrypt had silently failed !

Of course proper pattern is just : 

```go
os.WriteFile(pathString+".pdf", html, 0644)
err = api.DecryptFile(pathString+".pdf", "", conf)
if err != nil {
	fmt.Println("Can't decrypt ["+pathString+".pdf] : ", err)
}
```

And then we can see the errors, like (what you were encountering) the errors with the weird dates.

**How to solve the errors about weird dates** (still with PDFCPU)

As said before and after having checked the code, the pdfcpu is really not flexible at all (= it's very difficult to change it's behavior, or to use internal deep parts, like altering the validation).

However, in local, and before they would be able to handle the situation with these specific dates (or, better, if they would introduce a "NoDateValidation" mode, etc.), you can do the following : 

- in main folder, type `go mod vendor` : this will "copy" all the github dependencies inside your project, and then this is what will be used (and not anymore the OS global GO cache). By doing like, it's easy to "patch" the remote library
- open the `vendor/github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types/date.go` file in your editor and add this "if" in the `prevalidateDate` method (line 57, i would say) : 

```go
(...)
	// Remove trailing 0x00
	s = strings.TrimRight(s, "\x00")

	if strings.Contains(s, "-001-1-1-1-1-1-00") {
		s = "D:20000101100000Z" // YYYYMMDDHHmmSSZ
	}

	if relaxed {
(...)
```
The principle is obvious : this method is executed BEFORE the dates are parsed, and there we are "sanitizing" it, by removing the weird string and putting a valid date (i think a valid date is still needed, per the followup lines).

Like this, at least this error should be easily corrected.

Of course it's more a temporary hack than anything else, and a proper fix should be applied in the pdfcpu library (per the #910 issue in their repo).

However I would be curious to see if this is working on your side ;)

**Comment by SR-G** [comment]
> im no coder at all! how go i make a go file? i have go installed and visual studio code installed. im on OSX
> 
> thanks!

```bash
go build -o zinigo ZiniGo/main.go
```

**Comment by ER-EPR** [comment]
@SR-G It works quite well! I change it a little bit, by remove all dashes from the string. And now no error at all. Thanks very much
in pkg/pdfcpu/types/data.go line 57
```
if relaxed {
		// Accept missing "D:" prefix.
		// "YYYY" is mandatory
		s = strings.TrimPrefix(s, "D:")
		s = strings.TrimSpace(s)
		s = strings.ReplaceAll(s, ".", "")
		s = strings.ReplaceAll(s, "-", "0")
		s = strings.ReplaceAll(s, "\\", "")
		return s, len(s) >= 4
	}
```
I can see the download pages process was OK before this correction, it is the api.decrypt process fail and the following remove page and merge will too. I also use Stirling PDF docker container to decrypt and merge those pages before using it's pipeline function and success. But nothing is comparable to this perfect fix, thanks again.

**Comment by ER-EPR** [comment]
> @ER-EPR in my last experiments, it seemed that Zinio had stopped using the "Legacy" flag to mark files, and set the PDF. Unfortunately, my library isnt very big so none of my issues actually used this.
> 
> It almost seemed at some point like every other page was using a different password.
> 
> I have got a version using c# (Im a lot more familiar with c# than golang - this was just an experimental project for me) which I can try to get cleaned up and uploaded here.
> 
> Im not sure if makes sense to archive this repo and move to a new one, anyone have thoughts?

I think you can approve the pull request, merge it and you can integrate the code I provided above in getLibrary, and @SR-G's enhancements, then you would find it working flawlessly.

**Comment by TheAxeDude** [comment]
I will try to spend some time on that this weekend! Thank you :)

**Comment by dirty1200** [comment]
im too stupid to get this to work on osx....
so a new file update/download would be great :)

**Comment by shmimel** [comment]
Even after building, I'm still getting the "Route not found" error. Am I missing something here? I checked with the latest pull request and I have the most recent main.go file in the repo so I am a little confused.

**Comment by SR-G** [comment]
Not sure what you did (i don't understand your "i have the most recent main.go file in the repo" part - especially, you do NOT want the most recent one from this repo, but the one from the pull request + all the adjustements discussed in previous comments).

I tested 5 min ago and it's still working on my side.

Also i pushed my changes here (incl. the "vendor" stuff) (but there are still some uneeded tests inside the code), you should be able to grab it from there and build the binary (or use the one commited at the root, for linux)
https://github.com/SR-G/ZiniGo

**Comment by shmimel** [comment]
Thank you! That worked for me. I think I was getting a bit confused with how to grab the latest version of the repo, and I really appreciate your patience.

**Comment by ER-EPR** [comment]
@SR-G Some of the pages are not decrypted correctly by pdfcpu (most pages fine, but some will not show in pdfBox or LibreOffice, other PDF readers complain about some error, and it is not the date format issue, it also happen in PDFs with correct date.) so I finally change to use pdfbox in a docker container ([Stirling PDF](https://github.com/Stirling-Tools/Stirling-PDF) docker image) as a Rest API server. And the resulting PDF opens fine in most readers. The code to use the API turn out to be easy, I auto-generated it using [cURL to Go](https://github.com/curlconverter/curlconverter), and replace the input and output variables and it just works. And anyone can adapt to your setting by changing the URL `https://pdf.savorcare.com/` to the host IP or domain of your own server. And this Decrypt() func can replace the original api.DecryptFile by `err = Decrypt(pathString+".pdf", passwordToUse)`
```
func Decrypt(filename string, hash string) error {
	form := new(bytes.Buffer)
	writer := multipart.NewWriter(form)
	fw, err := writer.CreateFormFile("fileInput", filepath.Base(filename))
	if err != nil {
		log.Fatal(err)
		return err
	}
	fd, err := os.Open(filename)
	if err != nil {
		log.Fatal(err)
		return err
	}
	defer fd.Close()
	_, err = io.Copy(fw, fd)
	if err != nil {
		log.Fatal(err)
		return err
	}

	formField, err := writer.CreateFormField("password")
	if err != nil {
		log.Fatal(err)
		return err
	}
	_, err = formField.Write([]byte(hash))

	writer.Close()

	client := &http.Client{}
	req, err := http.NewRequest("POST", "https://pdf.savorcare.com/api/v1/security/remove-password", form)
	if err != nil {
		log.Fatal(err)
		return err
	}
	req.Header.Set("accept", "*/*")
	req.Header.Set("Content-Type", writer.FormDataContentType())
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
		return err
	}
	defer resp.Body.Close()
	bodyText, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
		return err
	}
	os.WriteFile(filename, bodyText, 0644)
	return err
}
```

**Comment by ER-EPR** [comment]
@SR-G But now I encounter a bigger problem, similar to [Text in PDF turns gibberish on copying but displays fine](https://superuser.com/questions/1124583/text-in-pdf-turns-gibberish-on-copying-but-displays-fine), the newly generated PDFs from this publisher seems to lack a custom font encode to Unicode translation table, which makes search, copy past and text to Audio(mostly needed) impossible. The text displayed fine in most PDF readers, but in LibreOffice it turns to gibberish, I right click the text box and look into the font it shows `SwntlfLtjblbSourceHanSansCN-Light-Identity-H` which I don't have in my system but seem to be this font [SourceHanSansCN](https://github.com/adobe-fonts/source-han-sans). I searched for a tool to reconstruct all fonts and add custom encode to Unicode translation table but no luck finding the solution. And I also need to find out the custom font the PDF using and install it in my system I guess, which I also don't know how (replace the font with the same encode but different name, it seems the PDF add a random string as prefix to the font name).  It would be so lucky of me if you could show me the correct way to do it.

**Comment by Qwerty31313** [comment]
Can someone update binaries in "built" -directory. Now they are 2 years old and not work. Still getting a "Route not found" error.

**Comment by QINGCHARLES** [comment]
I can confirm building @SR-G version on Linux worked for me and let me back up a magazine I needed. Thank you everyone!

**Comment by ChineseWelshman** [comment]
I don't currently have a working Linux machine at home... and it's been over 25 years since I've done any serious low-level programming. Any chance of someone updating the repo with updated binary executable builds, please?

**Comment by espeausco** [comment]
Hi there,
I had a running version with all the changes mentioned above till July 19th. Today I got the old error

❯ ./ZiniGo
Config file loaded
Username taken from config file
password taken from config file
chromepath taken from config file
Fingerprint taken from config file
Starting the application...
GettingLogin
GotLogin
Fetching Library
Fetching page:0
{"status":false,"error":{"message":"Invalid token","internal_code":"APPERR5555"}}
Terminating the application...

Any ideas? Changed API? 
Thanx
S.

**Comment by SR-G** [comment]
Same here :(

**Comment by QINGCHARLES** [comment]
I'm looking at it now... we'll see if it's possible to fix it.

**Comment by QINGCHARLES** [comment]
OK, it's definitely possible to fix it. It's not fatal. I'll upload when I have a fully working solution.

**Comment by QINGCHARLES** [comment]
ok, i fixed it and upgraded it so it works for every type of file now without resorting to using a browser.

(this is only for zinio unlimited... if you have the regular you'll have to hack some of the code like the urls and the newstand # i think)

i run it with: go run -mod=mod main.go -u='me@site.com' -p='mypass'

i tried pasting the code in here but it didn't work.. here's a link (says its 24 hours only): https://codeshare.io/2KjNvz -- someone else figure out how to paste it in here

**Comment by espeausco** [comment]
Great work, since I‘m Not using Unlimited I‘ll have a look at the changes this evening . Any particular thing to Look at?

**Comment by espeausco** [comment]
@QINGCHARLES 
thanx for your work - since I'm using not unlimited but the "normal" one - the URL of the APIs are very important. Since you changed a lot to the former code - can you please tell me the problems you encountered in the original code like change of URLs or different parameters?

**Comment by espeausco** [comment]
Perfect, runs also with regular account, just adjust baseURL. I also replaced newsstandID and the language settings. Works like a charm.
Thanks a lot @QINGCHARLES

**Comment by QINGCHARLES** [comment]
no problem. the only thing left is to get rid of the weird grey hamburger menu that still appears on some downloads. will try and get that fixed today

**Comment by QINGCHARLES** [comment]
this link expires in 24 hours, so if someone wants to grab it and host it somewhere... this code fixes all the known bugs, it works with both regular and unlimited accts, it decrypts all the previously undecryptable items, and it strips out the hamburger menus from the pdf streams that were in a lot of the pages

https://codeshare.io/5o0w3p

this is how i run it:
`go run -mod=mod file.go -u='name@example.com' -p='mypwd' -unlimited -thumbs -stripmenus`

use -unlimited if you want to login to that acct instead. -thumbs will also download thumbnails of every page. -stripmenus will get rid of hamburgers

**Comment by jfschroeder-dev** [comment]
I've put a copy of @QINGCHARLES code in a repository in my account:
<snip>
Thank you!

It's working pretty well. Some issues die midway through - will have to look into the debug code and see if I can figure out why. Also sessions die after awhile, but since this skips already downloaded issues that's not much of an issue.

My goal here is to get what I can from my library, so I might not care about a few misses. Might want to see if I can add something to obey the archived issue flag.

**Comment by QINGCHARLES** [comment]
I saw a comment, but it's gone now. If you find mags that don't work, let me know and I'll see if there is a way to fix it. But I need specific mag names.

**Comment by jfschroeder-dev** [comment]
> I saw a comment, but it's gone now. If you find mags that don't work, let me know and I'll see if there is a way to fix it. But I need specific mag names.

That was me. Seems I tripped their auto-abuse system and my account was suspended. They just reinstated my access, and I'm killing the upload out of caution.

I managed to get all 1104 issues in my account, but 8 of them had problems decrypting certain pages. 2006 issues of PC Magazine, Pl*yboy, others. After tweaking the code slightly I was able to download all of the pages for each issue, then use Acrobat to combine the files minus the ones with passwords. That's good enough for me, but not a real solution. Some of the pages it barfed on were Z* subscription offers, so not part of the original publication anyway.

For others edification, be careful what you upload - they didn't remove my upload, nor did they say I should "after manual review". I suspect the Qing already knew this!

**Comment by QINGCHARLES** [comment]
Yeah, I don't even wanna fork this or do a PR because this project is probably sitting on a knife edge of survival lol. Glad you got unlocked. If you can, email me the issue names so I can look at the code: hello@qingcharles.com -- I rewrote the whole thing as a Windows app last night and I'm seeing a whole bunch of new issues with the PDFs😂

**Comment by dreadbalaur** [comment]
> Yeah, I don't even wanna fork this or do a PR because this project is probably sitting on a knife edge of survival lol. Glad you got unlocked. If you can, email me the issue names so I can look at the code: [hello@qingcharles.com](mailto:hello@qingcharles.com) -- I rewrote the whole thing as a Windows app last night and I'm seeing a whole bunch of new issues with the PDFs😂

Pardon the noobie speak, but is there a plan to release it as a Windows app?

**Comment by QINGCHARLES** [comment]
I did in fact rewrite it as a Windows app. Hopefully it solves all the bugs that were out there. Send me an email and I'll upload it somewhere.

**Comment by Ninjastar64** [comment]
Hi everyone, is there a tutorial on getting it to work step by step for windows? I don't know what i'm doing...many thanks, Steve
